add testing script

diff --git a/home/.chezmoiscripts/run_once_after_install-100-term.sh.tmpl b/home/.chezmoiscripts/run_once_after_install-100-term.sh.tmpl
--- a/home/.chezmoiscripts/run_once_after_install-100-term.sh.tmpl
+++ b/home/.chezmoiscripts/run_once_after_install-100-term.sh.tmpl
@@ -1,16 +1,90 @@
-#!/bin/bash
+#!/usr/bin/env bash
+set -euo pipefail
 
-set -o errexit
-set -o nounset
+IFS=$'\n\t'
+TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
+readonly LOG_FILE="/tmp/$(basename "$0").${TIMESTAMP}.log"
 
-zsh_shell="/bin/zsh"
-if [ ! "$SHELL" = "$zsh_shell" ]; then
-  if [[ ! $(command -v zsh) ]]; then
-    echo "You must manually install zsh and set it as the default shell."
-    echo " 1. Install \"zsh\""
-    echo " 2. Run: chsh -s \"$zsh_shell\""
+#/ Usage:
+#/   term.sh
+#/
+#/ Description:
+#/   Sets the shell for the user.
+#/
+#/ Options:
+#/   --help:      Display this help message
+usage() { grep '^#/' "$0" | cut -c4-; }
+_print() {
+  case "$1" in
+    black) color="30" ;;
+    red) color="31" ;;
+    green) color="32" ;;
+    yellow) color="33" ;;
+    blue) color="34" ;;
+    magenta) color="35" ;;
+    cyan) color="36" ;;
+    white) color="37" ;;
+    *) echo "Unknown color: $1" >&2; return 1 ;;
+  esac
+
+  shift
+  while [ "$#" -gt 1 ]; do
+    case "$1" in
+      bold) color="${color};1" ;;
+      italic) color="${color};3" ;;
+      underline) color="${color};4" ;;
+      dim) color="${color};2" ;;
+      *) echo "Unknown option: $1" >&2; return 1 ;;
+    esac
+    shift
+  done
+
+  supported_colors=$(tput colors 2>/dev/null)
+  if [ "$supported_colors" -gt 8 ]; then
+    printf "\\033[${color}m%s\\033[0m\\n" "$1"
   else
-    # Change the default shell to zsh
-    chsh -s "$zsh_shell"
+    printf "%s\n" "$1"
   fi
+}
+info() { _print cyan "[INFO] $@" | tee -a "$LOG_FILE" >&2 ; }
+warning() { _print yellow "[WARNING] $@" | tee -a "$LOG_FILE" >&2 ; }
+error() { _print red "[ERROR] $@" | tee -a "$LOG_FILE" >&2 ; }
+fatal() { _print red bold "[FATAL] $@" | tee -a "$LOG_FILE" >&2 ; exit 1 ; }
+
+cleanup() {
+  echo "" >&2
+  _print white dim "Log: $LOG_FILE" >&2
+}
+
+main() {
+  zsh_shell="$(which zsh)"
+  if [ "$SHELL" = "$zsh_shell" ]; then
+    return
+  fi
+
+  if [[ ! $(command -v zsh) ]]; then
+    fatal "You must manually install zsh and set it as the default shell.\n 1. Install \"zsh\"\n 2. Run: chsh -s \"$zsh_shell\""
+  fi
+
+  info "▶ Setting the user shell to zsh"
+
+  if [ "$(id -u)" = "0" ]; then
+    Sudo=''
+    info "╍ Root user detected, skipping sudo for following commands"
+  elif which sudo >/dev/null 2>&1; then
+    Sudo='sudo'
+    info "╍ Sudo detected, using it for following commands"
+  else
+    Sudo=''
+    warning "╍ Cannot find 'sudo' so will attempt to run following commands without it"
+  fi
+
+  # Change the default shell to zsh
+  $Sudo chsh -s "$zsh_shell"
+}
+
+if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
+  trap cleanup EXIT
+  _print magenta dim "[$TIMESTAMP] Starting $(basename "$0")"
+  main "$@"
 fi
